### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by Zumbalamambo** [XiSHEN0220/NeighConsensus#1]
Could you please share the pre-trained model for testing?

**Comment by XiSHEN0220** [comment]
Hi,

**Comment by XiSHEN0220** [comment]
Hi, 
Sorry for the late reply,
I should have the model somewhere will let you know if I find it.

**Comment by Zumbalamambo** [comment]
@XiSHEN0220 may I ask if you've found the pretrained model? ;)

**Comment by XiSHEN0220** [comment]
Hi, 
I didn't manage to find the pre-trained weight. 
I can train one in 2-3 days if you can wait.
Otherwise, it is easy to run the training by following the instruction.

**Comment by Zumbalamambo** [comment]
@XiSHEN0220 yes, please.. i dont have gpu :(

**Comment by XiSHEN0220** [comment]
Hi, I updated a pre-trained model. 
You could try to run the demo [here](https://github.com/XiSHEN0220/NeighConsensus/blob/master/demoMatch.ipynb)

**Comment by Zumbalamambo** [comment]
@XiSHEN0220 Thank you! Could you please check if you can be able to extract the tar file? because it seems to be damaged :(

**Comment by XiSHEN0220** [comment]
I am able to download it and run the demo. 
What's your error message? 
Could you please tell me your Pytorch and Python version?
