### ISSUE TITLE
about the size of correlation map

### ISSUE THREAD

**Issue by gengenkai** [XiSHEN0220/NeighConsensus#2]
hi, thanks for sharing the code.
 I have a small question .  I run your demomatch.ipynb and observe that your input images are resized to 496x398 and then the output of your ncnet is tensor (1x1x23x31x23x31) . So how do you generate the correlation map 496x398x496x398 by the output of the ncnet(23x31x23x31) . Thank you.

**Comment by XiSHEN0220** [comment]
Hi, 
You have several choices to get the dense match from the sparse match:
1. you can do the bilinear interpolation, as used in the org NcNet paper. A simple implementation is to use F.interpolate
2. my implementation is a kind of weighted nearest neighbor in the ([Line 20, notebook](https://github.com/XiSHEN0220/NeighConsensus/blob/master/demoMatch.ipynb)). For a specific key point, I find 4 nearest neighbor points, then compute the distance for every point then compute a weight based on the distance.
