### ISSUE TITLE
Preparation of dataset

### ISSUE THREAD

**Issue by Zumbalamambo** [XiSHEN0220/NeighConsensus#3]
How do I prepare the custom dataset to train the model?

**Comment by XiSHEN0220** [comment]
You need to prepare a csv containing image path, correspondences etc. 
You could download what I have prepared for PF-Pascal to explore the data structure. 
`cd data/pf-pascal/`
`bash download.sh`

**Comment by Zumbalamambo** [comment]
@XiSHEN0220 May I ask how did you map the correspondence in the annotation? Is there any annotation tool to do so?

**Comment by XiSHEN0220** [comment]
The annotation is provided in the [PFPascal dataset](https://www.di.ens.fr/willow/research/proposalflow/). 

If you want to do annotation on your own dataset, you could try [LabelMe-NG](https://github.com/tianjiaoding/labelme-ng). 

BTW, the network is ResNet101 (large network), it might be slow to run on CPU.
